### PR TITLE
chore: add Dependabot

### PR DESCRIPTION
**Pull request by newpavlov**
This bot helps to keep dependencies up to date.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Please not, I really disklike dependabots PRs it generates a really unfortunate and unhelpful commit history in my experience.

**Comment by newpavlov** [comment]
Yeah, it also can be quite annoying. :) If we had a bot which would simply notify about outdated dependencies (e.g. via issues), I would use it instead.

**Comment by tarcieri** [comment]
One way to reduce dependabot churn is to turn down its alerting interval (e.g. from `daily` to `monthly`)

Also you can just use it for notifications... as soon as the relevant crates have been updated in any capacity it will auto-close obsolete PRs (I personally use it this way and find it rather helpful in that respect)

**Comment by dignifiedquire** [comment]
If we can set it to monthly I would be fine. I just don't want to end up with this constant flow of notifications, for both me and others who watch the repo, whith very little signal quality.

**Review by dignifiedquire — COMMENTED** [review]
thanks, lets try it

**Pull request merged**
