### PR TITLE
Make PrecomputedValues public

### PR DESCRIPTION
**Pull request by BrettMayson**
I need access to these values in order to store a custom private key format, this is preventing me from switching away from openssl

### CODE REVIEW

**Comment by tarcieri** [comment]
Is there a particular reason why you want to store these values instead of computing them on-the-fly?

The trend in RSA private key format design has been to store fewer precomputed values rather than more. Modern key formats store only `d` and can compute everything else from that and the public key.

**Comment by BrettMayson** [comment]
I need to store a custom format that I have no control over, which requires these values to be stored

**Comment by tarcieri** [comment]
Do you actually need to support multiprime RSA?

It would probably be worth keeping that out of the public API, especially as it currently has an odd definition owing to PKCS#1 also needing the CRT coefficient for two primes, so the current vector stores "additional CRT coefficients" beyond that one IIUC.

**Comment by newpavlov** [comment]
I don't think we should make the fields public. If you only need to read pre-computed values, then a bunch of getters should do the job. If you need to restore the values from serialized data, then we would need to think about validation.

**Comment by BrettMayson** [comment]
> Also: are you actually using multiprime RSA? (re: crt_values)

No, just `dp`, `dq` and `qinv`

**Comment by tarcieri** [comment]
In that case it sounds like you should just add read-only getter methods for those three

**Review by tarcieri — APPROVED** [review]

**Review by dignifiedquire — APPROVED** [review]

**Pull request merged**
